base_locale: en
locales: [en, de, ru, es]
search:
  paths:
  - app/
  - lib/
data:
  yaml:
    write:
      line_width: -1
ignore_inconsistent_interpolations:
 - 'rep.base.email.one'
 - 'rep.base.mailer.one'
